version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: nikolaygerasimov/kittygram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/media
  frontend:
    env_file: .env
    image: nikolaygerasimov/kittygram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
    depends_on:
      - backend
  gateway:
    image: nikolaygerasimov/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    depends_on:
      - backend
      - frontend
    volumes:
      - media:/media/
      - static:/static
